// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import java.awt.image.BufferedImage;

import robots.Robot;
import simbad.sim.CameraSensor;
import simbad.sim.RangeSensorBelt;
import simbad.sim.RobotFactory;

/************************************************************/
/**
 * 
 */
public class Camera {
	/**
	 * 
	 */
	private CameraSensor camera;
    private BufferedImage cameraImage;
    private int picCounter;

	/**
	 * 
	 * @param cameraSenor 
	 */
	public Camera(Robot r) {
		
		 this.camera = RobotFactory.addCameraSensor(r);
        
        // reserve space for image capture
        cameraImage = camera.createCompatibleImage();

	}

	/**
	 * 
	 * @return 
	 */
	public BufferedImage takePicture() {
        picCounter+= 1;

		if(picCounter < 2000){
	
	    	camera.copyVisionImage(cameraImage); 
			return this.cameraImage;

		}else{
			return null;
		}        
		
	}
	
	public int getPictureCount(){
		return this.picCounter;
	}
};
