// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package robots;

import javax.vecmath.Vector3d;

import RootElement.FileServer;
import robots.Robot;

/************************************************************/
/**
 * 
 */
public class RobotFactory {
	private static RobotFactory instance = null;
	
	private RobotFactory(){
		
	}
	
	/**
	 * 
	 * @param robotType 
	 * @return 
	 * @param fileServer 
	 */
	public static Robot createRobot(Vector3d coordinate, String name, FileServer fileServer) {
		return new ActingRobot(coordinate, name, fileServer);
	}
		
	public static RobotFactory getInstance(){
		if(instance == null){
			instance = new RobotFactory();
		}
		
		return instance; 
	}
};
