// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package robots;

/************************************************************/
/**
 * 
 */
public enum RobotStatus {
	/**
	 * 
	 */
	FIND_WALL,
	/**
	 * 
	 */
	COVER_WALL,
	/**
	 * 
	 */
	PAUSE,
	/**
	 * 
	 */
	FINISHED,
	/**
	 * 
	 */
	TAKE_PICTURES;
};
